// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MaintenanceWindowRepository is an autogenerated mock type for the MaintenanceWindowRepository type
type MaintenanceWindowRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, mw
func (_m *MaintenanceWindowRepository) Create(ctx context.Context, mw *domain.MaintenanceWindow) error {
	ret := _m.Called(ctx, mw)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MaintenanceWindow) error); ok {
		r0 = rf(ctx, mw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MaintenanceWindowRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpiredBefore provides a mock function with given fields: ctx, before
func (_m *MaintenanceWindowRepository) DeleteExpiredBefore(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMonitor provides a mock function with given fields: ctx, monitorID
func (_m *MaintenanceWindowRepository) FindByMonitor(ctx context.Context, monitorID string) ([]*domain.MaintenanceWindow, error) {
	ret := _m.Called(ctx, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMonitor")
	}

	var r0 []*domain.MaintenanceWindow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.MaintenanceWindow, error)); ok {
		return rf(ctx, monitorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.MaintenanceWindow); ok {
		r0 = rf(ctx, monitorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MaintenanceWindow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, monitorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindGlobal provides a mock function with given fields: ctx
func (_m *MaintenanceWindowRepository) FindGlobal(ctx context.Context) ([]*domain.MaintenanceWindow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindGlobal")
	}

	var r0 []*domain.MaintenanceWindow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.MaintenanceWindow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.MaintenanceWindow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MaintenanceWindow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsMonitorInMaintenance provides a mock function with given fields: ctx, monitorID, at
func (_m *MaintenanceWindowRepository) IsMonitorInMaintenance(ctx context.Context, monitorID string, at time.Time) (bool, error) {
	ret := _m.Called(ctx, monitorID, at)

	if len(ret) == 0 {
		panic("no return value specified for IsMonitorInMaintenance")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (bool, error)); ok {
		return rf(ctx, monitorID, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) bool); ok {
		r0 = rf(ctx, monitorID, at)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, monitorID, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMaintenanceWindowRepository creates a new instance of MaintenanceWindowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaintenanceWindowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaintenanceWindowRepository {
	mock := &MaintenanceWindowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
