// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// AssignChannel provides a mock function with given fields: ctx, monitorID, channelID
func (_m *NotificationRepository) AssignChannel(ctx context.Context, monitorID string, channelID string) error {
	ret := _m.Called(ctx, monitorID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for AssignChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, monitorID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateChannel provides a mock function with given fields: ctx, ch
func (_m *NotificationRepository) CreateChannel(ctx context.Context, ch *domain.NotificationChannel) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NotificationChannel) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChannel provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) DeleteChannel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindReminders provides a mock function with given fields: ctx
func (_m *NotificationRepository) FindReminders(ctx context.Context) ([]*domain.ReminderTarget, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindReminders")
	}

	var r0 []*domain.ReminderTarget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.ReminderTarget, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.ReminderTarget); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ReminderTarget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannel provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) GetChannel(ctx context.Context, id string) (*domain.NotificationChannel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 *domain.NotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.NotificationChannel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.NotificationChannel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannelsForMonitor provides a mock function with given fields: ctx, monitorID
func (_m *NotificationRepository) GetChannelsForMonitor(ctx context.Context, monitorID string) ([]domain.MonitorChannelAssignment, error) {
	ret := _m.Called(ctx, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelsForMonitor")
	}

	var r0 []domain.MonitorChannelAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.MonitorChannelAssignment, error)); ok {
		return rf(ctx, monitorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.MonitorChannelAssignment); ok {
		r0 = rf(ctx, monitorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MonitorChannelAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, monitorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasRecentSSLLog provides a mock function with given fields: ctx, monitorID, within
func (_m *NotificationRepository) HasRecentSSLLog(ctx context.Context, monitorID string, within time.Duration) (bool, error) {
	ret := _m.Called(ctx, monitorID, within)

	if len(ret) == 0 {
		panic("no return value specified for HasRecentSSLLog")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return rf(ctx, monitorID, within)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = rf(ctx, monitorID, within)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, monitorID, within)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LastSentAt provides a mock function with given fields: ctx, monitorID, channelID
func (_m *NotificationRepository) LastSentAt(ctx context.Context, monitorID string, channelID string) (time.Time, error) {
	ret := _m.Called(ctx, monitorID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for LastSentAt")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (time.Time, error)); ok {
		return rf(ctx, monitorID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) time.Time); ok {
		r0 = rf(ctx, monitorID, channelID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, monitorID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChannels provides a mock function with given fields: ctx
func (_m *NotificationRepository) ListChannels(ctx context.Context) ([]*domain.NotificationChannel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListChannels")
	}

	var r0 []*domain.NotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.NotificationChannel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.NotificationChannel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.NotificationChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLogs provides a mock function with given fields: ctx, channelID
func (_m *NotificationRepository) ListLogs(ctx context.Context, channelID string) ([]*domain.NotificationLog, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListLogs")
	}

	var r0 []*domain.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.NotificationLog, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.NotificationLog); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogNotification provides a mock function with given fields: ctx, log
func (_m *NotificationRepository) LogNotification(ctx context.Context, log *domain.NotificationLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for LogNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NotificationLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnassignChannel provides a mock function with given fields: ctx, monitorID, channelID
func (_m *NotificationRepository) UnassignChannel(ctx context.Context, monitorID string, channelID string) error {
	ret := _m.Called(ctx, monitorID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, monitorID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAssignmentTriggers provides a mock function with given fields: ctx, monitorID, channelID, triggers
func (_m *NotificationRepository) UpdateAssignmentTriggers(ctx context.Context, monitorID string, channelID string, triggers domain.AssignmentTriggers) error {
	ret := _m.Called(ctx, monitorID, channelID, triggers)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAssignmentTriggers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.AssignmentTriggers) error); ok {
		r0 = rf(ctx, monitorID, channelID, triggers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateChannel provides a mock function with given fields: ctx, ch
func (_m *NotificationRepository) UpdateChannel(ctx context.Context, ch *domain.NotificationChannel) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NotificationChannel) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
