// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NotificationSender is an autogenerated mock type for the NotificationSender type
type NotificationSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, ch, event, monitor
func (_m *NotificationSender) Send(ctx context.Context, ch *domain.NotificationChannel, event domain.NotificationEvent, monitor *domain.Monitor) error {
	ret := _m.Called(ctx, ch, event, monitor)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NotificationChannel, domain.NotificationEvent, *domain.Monitor) error); ok {
		r0 = rf(ctx, ch, event, monitor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationSender creates a new instance of NotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationSender {
	mock := &NotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
