// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// Notify provides a mock function with given fields: ctx, monitorID, event
func (_m *Notifier) Notify(ctx context.Context, monitorID string, event domain.NotificationEvent) {
	_m.Called(ctx, monitorID, event)
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
