// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReminderNotifier is an autogenerated mock type for the ReminderNotifier type
type ReminderNotifier struct {
	mock.Mock
}

// NotifyReminders provides a mock function with given fields: ctx
func (_m *ReminderNotifier) NotifyReminders(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NotifyReminders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReminderNotifier creates a new instance of ReminderNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReminderNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReminderNotifier {
	mock := &ReminderNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
