// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// SettingsRepository is an autogenerated mock type for the SettingsRepository type
type SettingsRepository struct {
	mock.Mock
}

// GetGeneral provides a mock function with given fields: ctx
func (_m *SettingsRepository) GetGeneral(ctx context.Context) (*domain.GeneralSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGeneral")
	}

	var r0 *domain.GeneralSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.GeneralSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.GeneralSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GeneralSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveGeneral provides a mock function with given fields: ctx, s
func (_m *SettingsRepository) SaveGeneral(ctx context.Context, s *domain.GeneralSettings) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for SaveGeneral")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GeneralSettings) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSettingsRepository creates a new instance of SettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsRepository {
	mock := &SettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
