// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StatsRepository is an autogenerated mock type for the StatsRepository type
type StatsRepository struct {
	mock.Mock
}

// GetDaily provides a mock function with given fields: ctx, monitorID, since
func (_m *StatsRepository) GetDaily(ctx context.Context, monitorID string, since time.Time) ([]*domain.StatsBucket, error) {
	ret := _m.Called(ctx, monitorID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetDaily")
	}

	var r0 []*domain.StatsBucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.StatsBucket, error)); ok {
		return rf(ctx, monitorID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.StatsBucket); ok {
		r0 = rf(ctx, monitorID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StatsBucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, monitorID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHourly provides a mock function with given fields: ctx, monitorID, since
func (_m *StatsRepository) GetHourly(ctx context.Context, monitorID string, since time.Time) ([]*domain.StatsBucket, error) {
	ret := _m.Called(ctx, monitorID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetHourly")
	}

	var r0 []*domain.StatsBucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.StatsBucket, error)); ok {
		return rf(ctx, monitorID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.StatsBucket); ok {
		r0 = rf(ctx, monitorID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StatsBucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, monitorID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMinutely provides a mock function with given fields: ctx, monitorID, since
func (_m *StatsRepository) GetMinutely(ctx context.Context, monitorID string, since time.Time) ([]*domain.StatsBucket, error) {
	ret := _m.Called(ctx, monitorID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetMinutely")
	}

	var r0 []*domain.StatsBucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.StatsBucket, error)); ok {
		return rf(ctx, monitorID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.StatsBucket); ok {
		r0 = rf(ctx, monitorID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StatsBucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, monitorID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStatsRepository creates a new instance of StatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsRepository {
	mock := &StatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
